version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: _
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      prod:
        dependency-type: production
        patterns:
          - "*"
      dev:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: _
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
