services:
  scylla-node:
    container_name: scylla-node
    image: scylladb/scylla:6.2
    command:
      - --smp=1
      - --memory=2GB
      - --overprovisioned=1
      - --developer-mode=1
      - --seeds=scylla-node
    ports:
      - "9042:9042"
    healthcheck:
      test:
        - CMD-SHELL
        - cqlsh -e "SHOW VERSION" || exit 1
      interval: 15s
      timeout: 30s
      retries: 15
      start_period: 30s
    networks:
      - scylla-network

  scylla-studio:
    container_name: scylla-studio
    image: scylla-studio:local
    build:
      context: .
      dockerfile: .docker/Dockerfile.alpine
    tty: true
    environment:
      - NEXT_PUBLIC_DOCKER_COMPOSE=1
      - NEXT_TELEMETRY_DISABLED=1
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
    volumes:
      - /home/node/app/node_modules
      - ./src:/home/node/app/src:rw
    ports:
      - "3000:3000"
    depends_on:
      scylla-node:
        condition: service_healthy
    networks:
      - scylla-network

networks:
  scylla-network:
    name: scylla-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: scylla-network
