name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      reason:
        description: "Write why you are requesting a manual release"
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PROVIDER: ghcr.io
  REPO_NAME: ${{ github.repository }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04
    # See https://github.com/actions/runner/issues/859#issue-766582646
    if: >
      (github.repository == 'basementdevs/scylla-studio') &&
      ((github.event_name == 'push' && contains(github.event.head_commit.message, '[CD]')) || (github.event_name == 'workflow_dispatch'))
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # 3.4.0
        with:
          registry: ${{ env.PROVIDER }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform "${{ env.PLATFORMS }}" \
            --label "org.opencontainers.image.source=https://github.com/${{ env.REPO_NAME }}" \
            --label "org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --tag "${{ env.IMAGE_NAME }}:latest" \
            --tag "${{ env.IMAGE_NAME }}:${{ github.sha }}" \
            --tag "${{ env.IMAGE_NAME }}:${{ github.ref_name }}" \
            --push \
            --progress=plain \
            --file .docker/Dockerfile \
            .
